server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://ca-api-todo-dev.internal.delightfultree-dce203d6.eastus2.azurecontainerapps.io;
        proxy_set_header Host ca-api-todo-dev.internal.delightfultree-dce203d6.eastus2.azurecontainerapps.io;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
